name = "gwlisa"
version = "0.1.0"
license = "license"
author = "Thomas"
maintainer = "thomas.biekoetter@desy.de"
copyright = "Copyright 2025, Thomas"

[build]
auto-executables = true
auto-tests = true
auto-examples = true
module-naming = false

[install]
library = true

[fortran]
implicit-typing = false
implicit-external = false
source-form = "free"

[dependencies]
openmp="*"
evortran = { git="https://gitlab.com/thomas.biekoetter/evortran.git", branch="fpm13", profile="release" }

[[test]]
name = "snr"
source-dir = "test"
main = "snr.f90"

[[executable]]
name = "copa_reconstr"
source-dir = "app/copa"
main = "reconstr.f90"
[executable.dependencies]
csv-fortran = { git="https://github.com/jacobwilliams/csv-fortran.git" }
copa = { git="https://github.com/thomasbiekoetter/copa.git", profile="release" }

[features]
debug.flags = "-fPIC -O0 -g "
debug.gfortran.flags = "-fbounds-check -fbacktrace -Wall -Wuninitialized -fmax-errors=1 -fcheck=all -ffpe-trap=invalid,zero,overflow"
debug.ifx.flags = "-check bounds -check pointer -traceback"
release.flags = "-O3"
release.gfortran.flags = "-march=native -fmax-errors=1 -ffixed-line-length-none -fno-range-check"
release.ifx.flags = "-xHost -march"

[profiles]
debug = ["debug"]
release = ["release"]
